[package]
name = "wireguard_tools_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes_size = "0.1.1"
ipnet = "2.5.0"